### ISSUE TITLE
Translation in german

### ISSUE THREAD

**Issue by tgorzka** [teejee2008/polo#101]
Is there already a German translation?

**Comment by teejee2008** [comment]
There are no translations as of now. I have updated the translation template in case you wish to translate it.
[https://github.com/teejee2008/polo/blob/master/polo.pot](https://github.com/teejee2008/polo/blob/master/polo.pot)

**Comment by tgorzka** [comment]
give me some days

**Comment by tgorzka** [comment]
Can I download the sources for compiling and testing? you can also send me the sources to my mail.

Thank you

**Comment by teejee2008** [comment]
Use **poedit** to convert the POT file to a PO file named **polo-de.po**. After translating the PO file, compile and install the MO file with following commands:

```
sudo mkdir -p /usr/share/locale/de/LC_MESSAGES
sudo msgfmt --check --verbose -o "/usr/share/locale/de/LC_MESSAGES/polo.mo" polo-de.po
```
Now when you start Polo it will display the German translation in the UI.

**Comment by tgorzka** [comment]
ok. After testing I send you the file.

**Comment by tgorzka** [comment]
you have mail ;-)

**Comment by teejee2008** [comment]
Translation has been included in Beta 7. Thanks!
