### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tgorzka** [teejee2008/polo#105]
Polo crash on start. System is Manjaro Cinnamon 64bit

Architecture: 64-bit
Host Name: $(hostname)

[Warning] Deleted invalid lock
Trash: query_completed

(polo-gtk:6934): Pango-CRITICAL **: pango_font_description_from_string: assertion 'str != NULL' failed

** (polo-gtk:6934): CRITICAL **: layout_box_get_panel_layout: assertion 'self != NULL' failed

Mount changed:
  name: mtp
  uuid: (null)
  can-eject: false
  can-unmount: true
  is-shadowed: true
  default-location: /run/user/1000/gvfs/mtp:host=%5Busb%3A002%2C005%5D
  icon: . GThemedIcon multimedia-player multimedia
  root: /run/user/1000/gvfs/mtp:host=%5Busb%3A002%2C005%5D
  guess-content-type:

Mount added:
  name: MT65xx Android Phone
  uuid: (null)
  can-eject: false
  can-unmount: true
  is-shadowed: false
  default-location: /run/user/1000/gvfs/mtp:host=%5Busb%3A002%2C005%5D
  icon: phone
  root: /run/user/1000/gvfs/mtp:host=%5Busb%3A002%2C005%5D
  guess-content-type:

Mount changed:
  name: MT65xx Android Phone
  uuid: (null)
  can-eject: false
  can-unmount: true
  is-shadowed: false
  default-location: /run/user/1000/gvfs/mtp:host=%5Busb%3A002%2C005%5D
  icon: phone
  root: /run/user/1000/gvfs/mtp:host=%5Busb%3A002%2C005%5D
  guess-content-type:

E: JSON-Daten müssen in UTF-8 kodiert sein

(polo-gtk:6934): Json-CRITICAL **: json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed

(polo-gtk:6934): Json-CRITICAL **: json_object_get_object_member: assertion 'object != NULL' failed

** (polo-gtk:6934): CRITICAL **: main_format_is_obsolete: assertion 'node != NULL' failed

(polo-gtk:6934): Json-CRITICAL **: json_object_get_int_member: assertion 'object != NULL' failed

(polo-gtk:6934): Json-CRITICAL **: json_object_get_array_member: assertion 'object != NULL' failed

(polo-gtk:6934): Json-CRITICAL **: json_array_get_elements: assertion 'array != NULL' failed
session restored: ============================================================
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by teejee2008** [comment]
Let me know if the crash still occurs with beta 8. It was working for me.

**Comment by teejee2008** [comment]
Fixed in Beta 10
