### ISSUE TITLE
Make shell configurable

### ISSUE THREAD

**Issue by makepanic** [teejee2008/polo#112]
I installed BETA 8 and it looks great so far.

Could you maybe make the shell configurable?
If it's possible one could remove fish and use the system wide shell (including its configuration).
Which would also allow to not to install fish while installing polo

Here's how spacefm does it (see editable Terminal select):
![20170703-100739](https://user-images.githubusercontent.com/1205444/27783823-0a600c72-5fd8-11e7-9fa8-79bc3c76b3f4.png)

**Comment by teejee2008** [comment]
Will be added in beta 9

**Comment by makepanic** [comment]
I don't know if it's available everywhere but `chsh -l` lists all available shells.
You could possibly use that to populate the options.

**Comment by teejee2008** [comment]
Thanks. Another way is to read /etc/shells but this file will not be present on all systems. I'll list the options in this file (if present) or provide an option to enter the path manually.

**Comment by teejee2008** [comment]
Added in beta 9
