### ISSUE TITLE
Information for building aur package

### ISSUE THREAD

**Issue by now-im** [teejee2008/polo#113]
I want to maintain this package in arch user repository. For this I need some information.

- Is this the list of dependencies and  does it not need gtk3?
`depends_arch:    libgee vte3 json-glib libxml2 ffmpeg mediainfo rsync pv p7zip tar xz gzip bzip2 fish qemu`

- What are packages needed for building and installing polo-file-manager(this will be the name in arch repo)?

- Any optional dependencies or conflicts?

- According to the other linux instruction, I executed the .sh file and nothing happened. After inspecting the code I got this:
```
#!/bin/bash

cd /tmp

wget http://launchpadlibrarian.net/279142125/p7zip_16.02+dfsg-1_amd64.deb http://launchpadlibrarian.net/279142124/p7zip-full_16.02+dfsg-1_amd64.deb http://launchpadlibrarian.net/279142120/p7zip-rar_16.02-1_amd64.deb

sudo apt-get remove p7zip{,-full,-rar}

sudo dpkg -i p7zip_16.02+dfsg-1_amd64.deb p7zip-full_16.02+dfsg-1_amd64.deb p7zip-rar_16.02-1_amd64.deb

echo 'done'
```

This script was clearly made for debian file packaging and I am seeing a lot .sh file in the source code.tar.gz.
Is there any suitable executable that can make this work painlessly in arch linux.

So, far I am loving the concept and maintaining this in aur is the first step of this becoming and official package in the future. You co-operation is very much needed and appreciated.

**Comment by teejee2008** [comment]
* Dependency packages:
`libgtk-3 libgee vte3 json-glib libxml2 ffmpeg mediainfo rsync pv p7zip tar xz gzip bzip2 qemu fish`
* Optional dependencies (Polo will run if these are not installed but various features will be missing or broken)
`ffmpeg mediainfo rsync pv p7zip tar xz gzip bzip2 qemu fish`
* Build dependencies (required for building on Ubuntu / Debian)
`autotools-dev valac libgtk-3-dev libgee-0.8-dev libvte-2.91-dev libjson-glib-dev libxml2-dev`
* No conflicts with other packages
* Don't use any of the scripts you find in the project directory. These are specific to my build environment and not useful on other systems.
* Build the project with: `make all` and Install with: `sudo make install`. If the build dependencies have been installed, it should build fine.

**Comment by now-im** [comment]
Kindly review these dependency problems. Some packages were easy to find but a lot of dev packages don't exist in arch. I have pointed out some alternatives. I need you to confirm if they are going to suffice or not.
```
Dependencies:
libgtk3 > gtk3
bzip2 > haskell-bzlib pbzip2 perl-compress-bzip2 (not sure which one needed)

Build Dependencies:
autotools-dev > autoconf
valac (i think you meant to write vala)
libvte > libvterm lilyterm (not sure if vte3 can complimant it or not)
libgtk-3-dev > gtk3 (no dev file)
libgee-0.8-dev > libgee (no dev file)
libvte-2.91-dev > vte 0.28.2 (available)
libjson-glib-dev > json-glib lib32-json-glib
libxml2-dev > libxml2 (no dev edition)
```

**Comment by teejee2008** [comment]
Dependencies:
libgtk3 > gtk3
bzip2 > haskell-bzlib pbzip2 perl-compress-bzip2 (not sure which one needed) **use pbzip2**

Build Dependencies:
autotools-dev > autoconf
valac (i think you meant to write vala) > **use vala if its available**
libvte > libvterm lilyterm (not sure if vte3 can complimant it or not) **use vte3**
libgtk-3-dev > gtk3 (no dev file) **-dev package is needed**
libgee-0.8-dev > libgee (no dev file) **-dev package is needed**
libvte-2.91-dev > vte 0.28.2 (available) **-dev package for vte or vte3 is needed**
libjson-glib-dev > json-glib lib32-json-glib
libxml2-dev > libxml2 (no dev edition) **-dev package is needed**

**Comment by BarbUk** [comment]
I have a pkgbuild to package the application from the .deb.
I will check the other dependencies and optional dependencies.

What about the license ?

```bash
# Maintainer: BarbUk
pkgname=polo-file-manager
pkgver=17.7
_channel=beta.8
pkgrel=1
pkgdesc="Preview of file manager"
arch=('x86_64')
url="http://www.teejeetech.in/search/label/polo"
depends=(gtk3 cairo-infinality libgee vte3-ng)
source=("polo-file-manager-v${pkgver}-${_channel}-amd64.deb::https://github.com/teejee2008/polo/releases/download/v${pkgver}-${_channel}/polo-file-manager-v${pkgver}-${_channel}-amd64.deb")
sha512sums=('475200c5c1da6ee273034036322fe89da707b60dcbd34f858cef92c2ff086f75b05a79b230887b3393e4918377a7887fa981dabb38b56ae7bc2ac2f4806a58ac')
license=('custom')

package() {
  msg2 "Extracting the data.tar.xz..."
  bsdtar -xf data.tar.xz -C "$pkgdir/"

  # Clean empty dir
  rm -r "$pkgdir"/usr/share/man
  rm -r "$pkgdir"/var
  rm -r "$pkgdir"/usr/share/polo/libs
  rm -r "$pkgdir"/usr/share/polo/actions
}
```

**Comment by teejee2008** [comment]
License is GPLv2

**Comment by BarbUk** [comment]
Thanks, will update the pkgbuild

**Comment by BarbUk** [comment]
Here is the updated pkgbuild with the correct license, url and description.

I'll check tonight the optional dependencies before releasing the pkgbuild on https://aur.archlinux.org.

```bash
# Maintainer: BarbUk
pkgname=polo-file-manager
pkgver=17.7
_channel=beta.8
pkgrel=1
pkgdesc="Modern, light-weight file manager for Linux with support for multiple panes, tabs, archive browsing/creation/extraction, and much more. (deb version)"
arch=('x86_64')
url="https://github.com/teejee2008/polo"
depends=(gtk3 cairo-infinality libgee vte3-ng)
source=("polo-file-manager-v${pkgver}-${_channel}-amd64.deb::https://github.com/teejee2008/polo/releases/download/v${pkgver}-${_channel}/polo-file-manager-v${pkgver}-${_channel}-amd64.deb")
sha512sums=('475200c5c1da6ee273034036322fe89da707b60dcbd34f858cef92c2ff086f75b05a79b230887b3393e4918377a7887fa981dabb38b56ae7bc2ac2f4806a58ac')
license=('GPLv2')

package() {
  msg2 "Extracting the data.tar.xz..."
  bsdtar -xf data.tar.xz -C "$pkgdir/"

  # Clean empty dir
  rm -r "$pkgdir"/usr/share/man
  rm -r "$pkgdir"/var
  rm -r "$pkgdir"/usr/share/polo/libs
  rm -r "$pkgdir"/usr/share/polo/actions
}
```

**Comment by now-im** [comment]
Someone has already done that. @teejee2008 you can close the issue, the objective has been completed.

**Comment by BarbUk** [comment]
Yep, not quick enough :)
https://aur.archlinux.org/packages/polo/
https://aur.archlinux.org/packages/polo-donation-plugins/

**Comment by teejee2008** [comment]
Someone uploaded the polo-donation-plugins as well to the repo :( 
I had shared this package with users who have donated to the project. Not sure if it's a mistake or if he knew what he was doing :(

**Comment by BarbUk** [comment]
It's just the pkgbuild to install the files that you send by mail. The .Deb are not included.

**Comment by teejee2008** [comment]
How is it useful to upload a pkgbuild to the AUR if the DEB or source is not included?

**Comment by BarbUk** [comment]
It's the aur way ☺️. You download the pkgbuild, put your .deb in the same dir and it build you an archlinux package that install the files in the right place.

If you use an aur package manager, you are notified when a new version is available. It's just a way to have all your packages managed by the package manager. You can safely uninstall all files with the package manager etc.

**Comment by FabioLolix** [comment]
Hi @teejee2008 I'm Fabio Loli,

I'm sorry for not having informed you before but I was short on time these days.

You must know that **your rights are respected** and I know what I'm doing.

The AUR, differently from Ubuntu's PPA or others repository, is a *repository of scripts* not of precompiled packages.

In the AUR there aren't uploaded any source, deb, rpm, run or similar files, only PKGBUILDs, which are instruction to build packages and if is the case .desktop, licenses, additional patches

Only who already have the DEB files can build and install polo-donation-plugins

Another similar case is [Cisco Packerttracer](https://aur.archlinux.org/packages/packettracer) , please note local:// in the "Sources", which mean the local computer where is built.

**Comment by teejee2008** [comment]
Hi Fabio, Sorry about my misunderstanding. I thought initially that the package was also uploaded. 
Thank you for adding the scripts to the AUR :)

**Comment by BarbUk** [comment]
Thanks @FabioLolix for the clarification.
@teejee2008 I think this issue can be closed.

**Comment by FabioLolix** [comment]
Hi @teejee2008 misunderstanding happens :)

I have actually some questions about packaging but I think it is better to open another issue?
