### ISSUE TITLE
Provide option to safely eject removable devices

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/polo#119]

**Comment by Vistaus** [comment]
I already see this option in Beta 9. Is this a different way of doing it?

**Comment by teejee2008** [comment]
There's an option to unmount each partition but there's no option to eject the device.

I was planning to add a eject button in the device header for removable devices. When clicked, this will sync any data waiting to be written, unmount all partitions on the device, and then power it off (LED will stop blinking on portable HDDs).

This is different from unmounting. Unmounted partitions are still visible to the system and may get auto-mounted again by other programs before the user has a chance to unplug it. Ejected devices on the other hand are not visible to the system and need to be unplugged and plugged-in again before it gets detected.

**Comment by Vistaus** [comment]
Ah, I see. Thanks for clarifying! :smile_cat:

**Comment by teejee2008** [comment]
Added in v18.3
