### ISSUE TITLE
More  loop device imgs Supports :-Squashfs,IMG etc.

### ISSUE THREAD

**Issue by Genxster1998** [teejee2008/polo#124]
I have a sfs image which is shown as mounted ,but not available to browse it.similarly i can't browse through .img extension loop devices.
The bug can be reproduced by mounting an .img or .sfs image of loop devices.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by teejee2008** [comment]
Added in v17.10
