### ISSUE TITLE
Sorting by type does not sort files and folders in alphabetical order

### ISSUE THREAD

**Issue by respock** [teejee2008/polo#125]
As in the topic, in the current version (17.7.1) sorting by type does not group files by type in alphabetical order. IMO sorting alphabetically should be default, it's how it works in most file managers. IDK, maybe I overlooked something in the preferences? Cheers.

**Comment by teejee2008** [comment]
Fixed in Beta 10. After sorting on type, items in each group will be sorted alphabetically by name.
