### ISSUE TITLE
Add UI option to have home button

### ISSUE THREAD

**Issue by makepanic** [teejee2008/polo#128]
Hi,
is it possible to have a home button in the pane header?

Right now if one is in a pane and wants to go back "home", one has to move to the global navigation bar.
There are already UI options to go back, up and open favorites but not to quickly open the home directory.

![20170724-090722](https://user-images.githubusercontent.com/1205444/28513122-1dbfbe56-7055-11e7-80e1-c0b951803f23.png)

Thanks

**Comment by teejee2008** [comment]
Added in Beta 10
