### ISSUE TITLE
Selection bar instead open on Return

### ISSUE THREAD

**Issue by dimmuboy** [teejee2008/polo#132]
Nice work, highly customizable but when I start real use I can't open any file with Enter button only double click. When I press Enter button at the bottom shows selection bar with "Return" text and radio button on Select.
What's wrong I have configured?
Current version: Beta9

**Comment by teejee2008** [comment]
Its a bug. Will be fixed in beta 10.

**Comment by teejee2008** [comment]
Fixed in Beta 10

**Comment by dimmuboy** [comment]
Hi, I have fresh installed Antergos with Gnome Shell with Polo v18.2 Beta but problem with enter into folders from keyboard is still here :/

**Comment by teejee2008** [comment]
Will be fixed in next release

**Comment by teejee2008** [comment]
Fixed in v18.3
