### ISSUE TITLE
Missing dep for video download feature

### ISSUE THREAD

**Issue by Lupul** [teejee2008/polo#139]
[Video download feature](https://github.com/teejee2008/polo/wiki/Video-Downloads) added in beta 10 requires mpsyt ([mps-youtube](https://github.com/mps-youtube/mps-youtube))

```
$ polo-yt list --url "https://..."
D: check_dependency(): mpsyt
E: Commands listed below are not available:

 > mpsyt

Please install required packages
```

In my case ubuntu 17.04 i have resolved with:
```
sudo apt install python3-pip
pip3 install mps-youtube
```

**Comment by teejee2008** [comment]
It doesn't actually. It uses only youtube-dl. I forgot to remove the check for mpsyt.

**Comment by teejee2008** [comment]
Updated in v17.9.1. I have sent the updated plugin by email.
