### ISSUE TITLE
Vertical space between icons

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/polo#14]
In icon view, the file / folder highlight (I'm not sure how to call it) and the vertical space between icons is inconsistent when in a folder with both files and folders, especially if there are long folder / file names. Screenshot: http://i.imgur.com/glxlz3y.png - Andrew

**Comment by Genxster1998** [comment]
Got it too on beta 9 ,the shortlisting the name of folders would be better ,the vertical space between  apps become sometimes horrible when a folder/file with large name appears ,hover quick info is already present ,thus showing full name is not worthy.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by teejee2008** [comment]
Fixed in Beta 10. File names will be ellipsized by default. There's a new option in Settings to display the whole name.
