### ISSUE TITLE
From keyboard still unusable

### ISSUE THREAD

**Issue by dimmuboy** [teejee2008/polo#140]
Select bar still got me going crazy. After open Polo I need to move throught items but I can't because when I press arrow Down I have unselected first item and after next press select bar shows. Select bar I can't close with Esc only I can go out from it with arrow Up but after enter to some folder Select bar kill me again.
Polo is so awesome file explorer but not usable for me now :(

**Comment by teejee2008** [comment]
Strange.. I didn't notice this issue. Will be fixed in the next update (Sep-24).

**Comment by dimmuboy** [comment]
Do you need some more details for fix it? I really like your work and want to try replace nautilus with it :)

**Comment by teejee2008** [comment]
Fixed in v17.9.2
