### ISSUE TITLE
Settings > UI > Items "Next" translation differs from used button

### ISSUE THREAD

**Issue by makepanic** [teejee2008/polo#144]
It's not a big issue but in the main ui, there's the `Forward` button which goes forward in the folder history.
If one wants to configure the ui, one has to use the `Next` checkbox to show/hide that button.
Maybe it's better to use one translation in both places?

![20170920-120947](https://user-images.githubusercontent.com/1205444/30795855-e9bd324e-a1cf-11e7-8ea4-97c5f52c3e71.png)

**Comment by teejee2008** [comment]
Fixed in v17.9.2
