### ISSUE TITLE
"Original location" column in Trash view (request)

### ISSUE THREAD

**Issue by Kzer-Za** [teejee2008/polo#147]
It would be nice if in Trash view there was a column displaying the original location (path) of trashed files/folders. Of course it's content would rarely fit in the column width, I suggest it mainly as a possibility to sort trashed files by their original location.

(Perhaps this request coincides with others, requesting the possibility to tune the view of different directories separately).

**Comment by teejee2008** [comment]
These columns were there previously. It seems to have disappeared in the last beta. 
Will be fixed in next update.

**Comment by teejee2008** [comment]
Added in v17.10
