### ISSUE TITLE
Polo reads a lot of info about subfolders

### ISSUE THREAD

**Issue by Kzer-Za** [teejee2008/polo#149]
I have an SSD and an HDD. When I open folders on my HDD in Polo it takes a lot of time because (I suppose, judging by the HDD noise) Polo caches a lot of info about subfolders, so when there is a lot of them with lots of files in subfolders, it significantly slowers down my work: if I don't go into these subfolders and stay just in the parent folder, all this caching is useless and just means lost time and excessive noise. In Thunar it may take more time when I go into a subfolder (on the HDD), but parent folders open much faster and quietly. Is it possible to make this reading of info about subfolders optional?

**Comment by teejee2008** [comment]
Fixed in v17.10

By default, subfolders will not be queried. You can enable the option from ```Settings > General > Performance > Query subfolders```
