### ISSUE TITLE
Use Esc to close type-ahead-find (request)

### ISSUE THREAD

**Issue by Kzer-Za** [teejee2008/polo#150]
When typing text in main view, a row in the bottom appears with the typed text, options to select or filter, and "Close" button. Currently the only way to close this row is to click with the mouse on the "Close" button or on some file. It would be nice if it disappeared on Esc key too.
(On additional note: perhaps a way to select/filter files only beginning with the typed text? In addition to the current way to select/filter files containing the typed text anywhere in the name)

**Comment by teejee2008** [comment]
Closing the selection bar with Esc key will be added in next update

**Comment by teejee2008** [comment]
Added in v17.10
