### ISSUE TITLE
Preview pane - Feature

### ISSUE THREAD

**Issue by malliwi88** [teejee2008/polo#156]
Hi nice job

I'm thinking that a preview panel will be a nice feature for Polo such as [Windows preview pane](https://www.eightforums.com/tutorials/35233-preview-pane-hide-show-preview-handlers-windows.html)
![](https://www.eightforums.com/attachments/tutorials/31499d1384071211-preview-pane-hide-show-preview-handlers-windows-preview_pane_preview_handlers-off.jpg)

Some tools aditionally support [document convertion](https://github.com/dagwieers/unoconv) for preview docs, such as gloobus-preview, that support LibreOffice/OpenOffice docs  [Unoconv + gloobus-preview](http://www.edivaldobrito.com.br/como-ativar-a-visualizacao-rapida-de-arquivo-no-nautilus/)

## Some usefull links
* [Universal Office Converter](https://github.com/dagwieers/unoconv)
* [Another interesting preview pane](https://n00bsonubuntu.net/content/top-add-ons-for-nautilus/)
* [Nice Nautilius feature](http://www.techdrivein.com/2010/10/nautilus-elementary-in-ubuntu-maverick.html)
* [GNOME Twitch integration](https://github.com/vinszent/gnome-twitch)
![](https://raw.githubusercontent.com/vinszent/gnome-twitch/master/data/screenshots/scrot_streams.png)

Thanks for paid attention.

**Comment by Cybolic** [comment]
Maybe this should be merged with #3?

**Comment by teejee2008** [comment]
Added in v18.3
