### ISSUE TITLE
Feature drag and drop multiple files

### ISSUE THREAD

**Issue by malliwi88** [teejee2008/polo#157]
Hi

*Behavior of problem*: It's very common drag and drops songs over media player (at least for me) and for many other tasks, clear.

Please, only try to do this task (ex: image), select multiple files and drag and a drop in another folder/location using polo and you can see the problem
![](https://help.blackboard.com/sites/default/files/bb_assets_embed/15000/course_files_drag_drop.png)

Thx,  Best regards.

**Comment by fbg13** [comment]
There is no support for drag and drop yet #27

**Comment by teejee2008** [comment]
Closing duplicate
