### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by imilos** [teejee2008/polo#167]
Polo FM works perfectly on Fedora 27, but I'm just wondering if there is a stramlined uninstall procedure, since there is no Polo RPM?

**Comment by grturner** [comment]
Run `polo-uninstall` . By the way, polo is packaged on COPR.  https://copr.fedorainfracloud.org/coprs/grturner/Polo/

**Comment by imilos** [comment]
Thanks a lot! Polo is such a refreshment!
