### ISSUE TITLE
Unresolved package dependency on F27

### ISSUE THREAD

**Issue by aflatoon2874** [teejee2008/polo#171]
DNF failed to install polo on F27. Could not resolve providers for gvfs-backends package dependency. I believe gvfs backends are already installed in F27 as separate packages. 

Please help

**Comment by stickster** [comment]
Fedora 27 doesn't provide this package, it's provided in a COPR that's not an official build, so this is not a Fedora problem. Neither is this problem the responsibility of the upstream developer. It's purely a problem for which the individual COPR owner is responsible. You're free to contact that owner, grturner, through their COPR info at https://copr.fedorainfracloud.org/coprs/grturner/Polo/package/polo/ .

**Comment by illucent** [comment]
same issue

```
$ dnf install polo
Error: 
 Problem: conflicting requests
  - nothing provides gvfs-backends needed by polo-18-1_beta.fc27.x86_64
```

**Comment by grturner** [comment]
I'm looking into it.

**Comment by stickster** [comment]
I also notified the COPR owner about the problem on their end.

**Comment by grturner** [comment]
That'd be me. I replied to your email however the my on campus wifi does not play well with mailspring.

**Comment by grturner** [comment]
https://copr.fedorainfracloud.org/coprs/grturner/Polo/build/720318/

If anyone out there cares to test it, I'd much appreciate it.

**Comment by baoboa** [comment]
works for me on fedora27 x86_64 , i suppose this issue should be closed.

Great program by the way.

**Comment by brianread108** [comment]
Also works for me on Fed27 x68_64

**Comment by gombosg** [comment]
It's working for me, too, I suggest closing this.

**Comment by illucent** [comment]
It works!
