### ISSUE TITLE
Segmentations fault 18.2 beta

### ISSUE THREAD

**Issue by aldorgan** [teejee2008/polo#172]
when trying to start polo-gtk on a debian system after the install i get this in the terminal:

$ polo-gtk
Architecture: 64-bit
Host Name: Laptop
CPU Cores: 4
RAM: 7895 MB
[Warning] Deleted invalid lock
Segmentationfault

**Comment by teejee2008** [comment]
Run polo-gtk with --debug option and send me the output
`polo-gtk --debug`

**Comment by aldorgan** [comment]
i reinstalled Polo and rebooted the computer then it started up correctly not sure what was wrong with it, but it seems to work, so you can close this issue for now :)
