### ISSUE TITLE
Opening file properties panel crashes polo

### ISSUE THREAD

**Issue by PrSdNt** [teejee2008/polo#194]
Whenever I open the file properties panel polo crashes.

Polo 18.3 BETA
Fedora 28

**Comment by ivanmlerner** [comment]
I have the same issue, I will post debugging output when I get home.

**Comment by ivanmlerner** [comment]
This seems to be fixed in version 18.6.

**Comment by wllmcdl** [comment]
it was happening to me even on the 18.6 version, but it stopped after installing groot

**Comment by Paulikid** [comment]
issue still exists here on v.18.6, even after installing groot. OS is Arch linux.

**Comment by teejee2008** [comment]
This is fixed in v18.8. Please reopen if it still occurs.
