### ISSUE TITLE
Sidebar should retain fixed width when window is resized

### ISSUE THREAD

**Issue by chrisjbillington** [teejee2008/polo#195]
The width of the sidebar currently seems to be set as a fraction of the total window width.

This means that if you go from a small window with an appropriately sized sidebar:

![polo_small](https://user-images.githubusercontent.com/1044087/40217445-17beeb76-5ab0-11e8-90b9-daaeb10391bc.png)
To a maximised window:
![polo-big](https://user-images.githubusercontent.com/1044087/40217466-36eb0ba6-5ab0-11e8-98e2-26c643721481.png)

The sidebar becomes excessively large. Similarly if you resize it when maximised to something sensible, then unmaximise the window, it becomes excessively small.

**Comment by teejee2008** [comment]
Fixed in v18.6
