### ISSUE TITLE
Type-ahead matches unexpected files

### ISSUE THREAD

**Issue by chrisjbillington** [teejee2008/polo#197]
When you start typing and polo selects files, it was unexpected to me that it would select files that contained the term I had typed anywhere within their names, and not just at the start.

For example if I type 'm' in my home directory I get ''Documents" as well as "Music" selected. I would have expected only "Music".

I understand it's a search that is selecting all matching files, but it is unexpected nonetheless. Perhaps the "filter" option could have this behaviour and the "select" option could match only the start of the strings?

The matching of unexpected files makes it difficult to use the type-ahead feature to navigate folder hierarchies using the keyboard only.

**Comment by chrisjbillington** [comment]
By the way this is a beautiful file browser!

**Comment by teejee2008** [comment]
Fixed in v18.6

**Comment by chrisjbillington** [comment]
Thank you! This is excellent news.
And thanks for fixing the other bugs I reported. I'll give Polo another try now that these minor issues are resolved.
