### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by zenmaster24** [teejee2008/polo#199]
Hi,

This is a great looking file manager! 
I was wondering if drag n drop was coming any time soon?
Also, is there a way for either a) polo to remember the window size and position of the last session, or b) not remember the last session's folder and open in $HOME or some specified dir?

Thanks for such a nice looking file manager!

**Comment by zenmaster24** [comment]
thankyou teejee2008 - remember last session is unticked and working as expected :)
would you let me know if there is a way to remember credentials for smb shares saved in the bookmarks? this works in files, but i have to re-authenticate each time i open polo

**Comment by teejee2008** [comment]
Polo doesn't save any credentials entered in the application as storing and securing the credentials involves a security risk.
