### ISSUE TITLE
Left and right sidebares shouldn't scale with window size

### ISSUE THREAD

**Issue by linuxundich** [teejee2008/polo#203]
I think the two sidebars (bookmarks and file informations) should not resize with the width of the application window. Usually I set them up, so I see the information I like to see (e.g. the bookmarks). But when i put polo into fullscreen mode, the two sidebars get huge and waist a lot of screen space.

https://webmshare.com/VGXYP

**Comment by linuxundich** [comment]
Sorry, there is already an open issue: https://github.com/teejee2008/polo/issues/195

**Comment by teejee2008** [comment]
Fixed in v18.6
