### ISSUE TITLE
Call qemu-system-x86_64 instead of kvm?

### ISSUE THREAD

**Issue by linuxundich** [teejee2008/polo#205]
I try to run a VM via KVM from inside Polo under Arch Linux. The external tools assistant tells me there is no kvm command on my system. He's right, under arch linux there is no kvm command i could install. Everything is handled by qemu. So when I try to start a vm inside qcow file, i get the follow error inside a terminal...

/tmp/polo/6JIk5JPg/15284676443780112840/1528467644983072008.sh: Zeile 4: kvm: Kommando nicht gefunden.

When i check the file, the call is...

kvm -enable-kvm -cpu host -smp 2 -vga std -m 2048M -netdev user,id=vmnic -device virtio-net,netdev=vmnic -smb '/home/toff/Öffentlich' -hda '/home/toff/QEMU/ubuntu.qcow'

So, when I replace kvm by qemu-system-x86_64 my vm starts up.

$ qemu-system-x86_64 -enable-kvm -cpu host -smp 2 -vga std -m 2048M -netdev user,id=vmnic -device virtio-net,netdev=vmnic -smb '/home/toff/Öffentlich' -hda '/home/toff/QEMU/ubuntu.qcow'
qemu-system-x86_64: -smb /home/toff/Öffentlich: The -smb option is deprecated. Please use '-netdev user,smb=...' instead.

I'm not sure: is the kvm call deprecated and qemu-system-x86_64 the way to go, or is this an Arch-thing?

**Comment by teejee2008** [comment]
Install the qemu-kvm package. That will fix the issue.

**Comment by linuxundich** [comment]
There is no package qemu-kvm in Arch, nor is there a executable called "kvm".

```
$ sudo pkgfile -u
:: Updating 4 repos...
  download complete: multilib             [   280,7 KiB   851K/s  3 remaining]
  download complete: core                 [   748,2 KiB   920K/s  2 remaining]
  download complete: extra                [     7,2 MiB  1489K/s  1 remaining]
  download complete: community            [    17,3 MiB  2,10M/s  0 remaining]
:: download complete in 8,24s             <    25,6 MiB  3,10M/s  4 files    >
:: waiting for 1 process to finish repacking repos...
$ pkgfile kvm
$ 

```

**Comment by teejee2008** [comment]
Create a symlink to qemu-system-x86_64 in /usr/bin:

`sudo ln -s /usr/bin/qemu-system-x86_64 /usr/bin/kvm`

Check the path for qemu-system-x86_64 with `which qemu-system-x86_64` before running the baove command

**Comment by SolarAquarion** [comment]
@linuxundich @teejee2008 it's built right into the kernel https://wiki.archlinux.org/index.php/KVM

**Comment by teejee2008** [comment]
KVM is a feature of the Linux kernel but it requires user-space tools for using it. kvm and qemu-system-x86_64 are tools for running VMs. Symlinking qemu-system-x86_64 with kvm will solve the issue with Polo.

**Comment by FabioLolix** [comment]
@linuxundich 
Link creation has been added in the AUR pkgbuild for the polo plugins
