### ISSUE TITLE
Fedora 27/28 copr

### ISSUE THREAD

**Issue by imilos** [teejee2008/polo#209]
Dear Mr. George,

Just to let you know that I've built https://copr.fedorainfracloud.org/coprs/mivanovic/Polo/ for Fedora 27/28 for Polo 18.6beta. If you want, you can include it where you find suitable... Thanks on your great work!

Kind regards
Milos

**Comment by teejee2008** [comment]
Thanks!

**Comment by imilos** [comment]
Updated to 18.8 BETA.
