### ISSUE TITLE
Polo sometimes doesn't start...

### ISSUE THREAD

**Issue by wllmcdl** [teejee2008/polo#214]
when i try to open Polo sometimes it doesn't work, so I opened it using terminal and I get these errors:

[Warning] Deleted invalid lock

(polo-gtk:7107): Gdk-CRITICAL **: 11:52:44.721: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:7107): GLib-CRITICAL **: 11:52:44.859: g_strsplit: assertion 'string != NULL' failed
Segmentation fault (core dumped)

(polo-gtk:7377): Gtk-CRITICAL **: 11:58:41.288: gtk_tree_model_foreach: assertion 'GTK_IS_TREE_MODEL (model)' failed

**Comment by RogueScholar** [comment]
Running Kubuntu 18.04 on a Lenovo ThinkPad T420s. I'm running into the same issue, but only when opening Polo from the Launcher or terminal, when another application calls for a file manager window to open (Polo is set as my default file manager in the Plasma System Settings) it works fine and dandy. Here's the output when attempting to open from the terminal:

(polo-gtk:17078): Pango-CRITICAL **: 13:40:53.730: pango_font_description_from_string: assertion 'str != NULL' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.091: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.162: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.213: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.414: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.473: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.528: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.587: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.646: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.716: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.775: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed

(polo-gtk:17078): Gdk-CRITICAL **: 13:40:54.835: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
[13:40:55.173] MainWindow: save_session()
double free or corruption (fasttop)
[1]    17078 segmentation fault (core dumped)  polo-gtk

I just sent in my donation for the extra plugins today so any ideas you have for troubleshooting this would be most appreciated. Can't wait to enjoy all the new goodies.

**Comment by teejee2008** [comment]
The set_cursor() issue is fixed in v18.8. Let me know in case this still occurs with v18.8

**Comment by MikeWallaceDev** [comment]
I didn't see the logs, I can't tell if it's the same error, but I can tell you that sometimes 18.8 does not start. It does start on 2nd or 3rd try.
