### ISSUE TITLE
Change the default language

### ISSUE THREAD

**Issue by asitemade4u** [teejee2008/polo#225]
Is there a way to change the default language -- in a parameter file, obviously, as I could not find it in the GUI.
But where?
PS. I am French living in the US and although my Ubuntu based computer works in French, I sometimes find it better to work in English -- mostly when the translation is incomplete or flawed.
Thanks, S.

**Comment by teejee2008** [comment]
Delete the following file
```
sudo rm -vf /usr/share/locale/fr/LC_MESSAGES/polo.mo
```

**Comment by asitemade4u** [comment]
Thank you so much. When I have time I will fix the issues in the French 
translation (a lot).

Stephen Sinclair
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
email: stephen@aSiteMade4U.com <mailto:stephen@aSiteMade4U.com>
web: aSiteMade4U.com 
<http://asitemade4u.com/?utm_source=stephen_email&amp;utm_medium=email&amp;utm_content=logolink&amp;utm_campaign=current_stephens_email>
cell: (914) 334-2929
