### ISSUE TITLE
Add support to browse and sync cloud accounts using rclone utility

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/polo#25]

**Comment by Vistaus** [comment]
I would love this! I'm not a dev, but instead of rclone, you might also want to take a look at how Nautilus devs are doing it: http://www.omgubuntu.co.uk/2017/07/nautilus-dropbox-cloud-service-integration

**Comment by teejee2008** [comment]
Its coming soon. I've started working on it, but it will take some time to finish.
Doing it the Nautilus way is more time consuming. Using rclone will save me a lot of time. Also rclone is stable and well tested, so it will be better to use it than reinvent the wheel.
