### ISSUE TITLE
cannot install Linux Mint 19.1 Tessa

### ISSUE THREAD

**Issue by bdkdavid** [teejee2008/polo#268]
**Describe the bug**

**To Reproduce**
3. Error message

**Expected behavior**

**Screenshots**

**System:**
 - Linux Distribution Name and Version: [e.g. Ubuntu 16.04]
 - Desktop [e.g. MATE, XFCE]
 - Application Version [e.g. v18.8]

***This is a free application created in my spare time. Consider making a donation if you need support for an issue***

[![](https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif)](https://www.paypal.com/cgi-bin/webscr?business=teejeetech@gmail.com&cmd=_xclick&currency_code=USD&item_name=Polo%20Donation)

**Comment by bdkdavid** [comment]
I bought the plugins attempted to install them: 

I used both files: 
I have an Intel processor
the following error:

17:17:43 polo-donation-plugins-v18.8 $ sudo apt install ./polo-donation-plugins-v18.8-i386.deb
[sudo] password for bri:               
Sorry, try again.
[sudo] password for bri:               
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'polo-donation-plugins:i386' instead of './polo-donation-plugins-v18.8-i386.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 polo-donation-plugins:i386 : Depends: pngcrush:i386 but it is not going to be installed
                              Depends: youtube-dl:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.
17:18:59 polo-donation-plugins-v18.8 $ sudo apt install ./polo-donation-plugins-v18.8-amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'polo-donation-plugins' instead of './polo-donation-plugins-v18.8-amd64.deb'
polo-donation-plugins is already the newest version (18.8).
The following packages were automatically installed and are no longer required:
  gir1.2-gnomekeyring-1.0 libcryptui0a libgnome-keyring-common libgnome-keyring0 libllvm7 libsecret-1-dev
  linux-headers-4.15.0-23 linux-headers-4.15.0-23-generic linux-headers-4.15.0-29 linux-headers-4.15.0-29-generic
  linux-headers-4.15.0-32 linux-headers-4.15.0-32-generic linux-headers-4.15.0-33 linux-headers-4.15.0-33-generic
  linux-headers-4.15.0-34 linux-headers-4.15.0-34-generic linux-headers-4.15.0-36 linux-headers-4.15.0-36-generic
  linux-headers-4.15.0-38 linux-headers-4.15.0-38-generic linux-headers-4.15.0-39 linux-headers-4.15.0-39-generic
  linux-headers-4.15.0-42 linux-headers-4.15.0-42-generic linux-headers-4.15.0-43 linux-headers-4.15.0-43-generic
  linux-headers-4.15.0-44 linux-headers-4.15.0-44-generic linux-headers-4.15.0-45 linux-headers-4.15.0-45-generic
  linux-headers-4.15.0-46 linux-headers-4.15.0-46-generic linux-headers-4.15.0-47 linux-headers-4.15.0-47-generic
  linux-headers-4.15.0-48 linux-headers-4.15.0-48-generic linux-headers-4.15.0-50 linux-headers-4.15.0-50-generic
  linux-image-4.15.0-23-generic linux-image-4.15.0-29-generic linux-image-4.15.0-32-generic
  linux-image-4.15.0-33-generic linux-image-4.15.0-34-generic linux-image-4.15.0-36-generic
  linux-image-4.15.0-38-generic linux-image-4.15.0-39-generic linux-image-4.15.0-42-generic
  linux-image-4.15.0-43-generic linux-image-4.15.0-44-generic linux-image-4.15.0-45-generic
  linux-image-4.15.0-46-generic linux-image-4.15.0-47-generic linux-image-4.15.0-48-generic
  linux-image-4.15.0-50-generic linux-modules-4.15.0-23-generic linux-modules-4.15.0-29-generic
  linux-modules-4.15.0-32-generic linux-modules-4.15.0-33-generic linux-modules-4.15.0-34-generic
  linux-modules-4.15.0-36-generic linux-modules-4.15.0-38-generic linux-modules-4.15.0-39-generic
  linux-modules-4.15.0-42-generic linux-modules-4.15.0-43-generic linux-modules-4.15.0-44-generic
  linux-modules-4.15.0-45-generic linux-modules-4.15.0-46-generic linux-modules-4.15.0-47-generic
  linux-modules-4.15.0-48-generic linux-modules-4.15.0-50-generic linux-modules-extra-4.15.0-23-generic
  linux-modules-extra-4.15.0-29-generic linux-modules-extra-4.15.0-32-generic linux-modules-extra-4.15.0-33-generic
  linux-modules-extra-4.15.0-34-generic linux-modules-extra-4.15.0-36-generic linux-modules-extra-4.15.0-38-generic
  linux-modules-extra-4.15.0-39-generic linux-modules-extra-4.15.0-42-generic linux-modules-extra-4.15.0-43-generic
  linux-modules-extra-4.15.0-44-generic linux-modules-extra-4.15.0-45-generic linux-modules-extra-4.15.0-46-generic
  linux-modules-extra-4.15.0-47-generic linux-modules-extra-4.15.0-48-generic linux-modules-extra-4.15.0-50-generic
  seahorse-daemon
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
17:20:49 polo-donation-plugins-v18.8 $ sudo apt install ./polo-donation-plugins-v18.8-i386.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'polo-donation-plugins:i386' instead of './polo-donation-plugins-v18.8-i386.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 polo-donation-plugins:i386 : Depends: pngcrush:i386 but it is not going to be installed
                              Depends: youtube-dl:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by bdkdavid** [comment]
bri@penguin:~$  cat /etc/linuxmint/info
RELEASE=19.1
CODENAME=tessa
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 19.1 Tessa"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_tessa_cinnamon_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_tessa_cinnamon.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 19.1 Cinnamon

**Comment by teejee2008** [comment]
This is 32-bit or 64-bit system?

Run `uname -m`

**Comment by bdkdavid** [comment]
x86_64

**Comment by teejee2008** [comment]
You have a 64-bit system. Install the 64-bit package.

sudo apt install ./polo-donation-plugins-v18.8-amd64.deb

**Comment by teejee2008** [comment]
Remove the 32-bit version before installing the 64-bit package

sudo apt purge polo-donation-plugins:i386

**Comment by bdkdavid** [comment]
bri@penguin:~$ sudo apt purge polo-donation-plugins:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package polo-donation-plugins:i386

**Comment by bdkdavid** [comment]
bri@penguin:~/Documents/polo-donation-plugins-v18.8$ sudo apt purge ./polo-donation-plugins-v18.8-i386.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'polo-donation-plugins:i386' instead of './polo-donation-plugins-v18.8-i386.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 polo-donation-plugins:i386 : Depends: pngcrush:i386 but it is not going to be installed
                              Depends: youtube-dl:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by teejee2008** [comment]
Try:
sudo apt purge polo-donation-plugins
sudo apt-get install -f

**Comment by bdkdavid** [comment]
still not working

**Comment by bdkdavid** [comment]
![Screenshot from 2019-07-21 08-40-46](https://user-images.githubusercontent.com/52471052/61593368-84ea4a80-ab93-11e9-9507-fca5ca47e827.png)

youtube dll

**Comment by bdkdavid** [comment]
OK! worked!

bri@penguin:~/Documents/polo-donation-plugins-v18.8$ sudo apt install ./polo-donation-plugins-v18.8-amd64.deb
[sudo] password for bri:               
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'polo-donation-plugins' instead of './polo-donation-plugins-v18.8-amd64.deb'
The following packages were automatically installed and are no longer required:
  gir1.2-gnomekeyring-1.0 libcryptui0a libgnome-keyring-common
  libgnome-keyring0 libllvm7 libsecret-1-dev linux-headers-4.15.0-23
  linux-headers-4.15.0-23-generic linux-headers-4.15.0-29
  linux-headers-4.15.0-29-generic linux-headers-4.15.0-32
  linux-headers-4.15.0-32-generic linux-headers-4.15.0-33
  linux-headers-4.15.0-33-generic linux-headers-4.15.0-34
  linux-headers-4.15.0-34-generic linux-headers-4.15.0-36
  linux-headers-4.15.0-36-generic linux-headers-4.15.0-38
  linux-headers-4.15.0-38-generic linux-headers-4.15.0-39
  linux-headers-4.15.0-39-generic linux-headers-4.15.0-42
  linux-headers-4.15.0-42-generic linux-headers-4.15.0-43
  linux-headers-4.15.0-43-generic linux-headers-4.15.0-44
  linux-headers-4.15.0-44-generic linux-headers-4.15.0-45
  linux-headers-4.15.0-45-generic linux-headers-4.15.0-46
  linux-headers-4.15.0-46-generic linux-headers-4.15.0-47
  linux-headers-4.15.0-47-generic linux-headers-4.15.0-48
  linux-headers-4.15.0-48-generic linux-headers-4.15.0-50
  linux-headers-4.15.0-50-generic linux-image-4.15.0-23-generic
  linux-image-4.15.0-29-generic linux-image-4.15.0-32-generic
  linux-image-4.15.0-33-generic linux-image-4.15.0-34-generic
  linux-image-4.15.0-36-generic linux-image-4.15.0-38-generic
  linux-image-4.15.0-39-generic linux-image-4.15.0-42-generic
  linux-image-4.15.0-43-generic linux-image-4.15.0-44-generic
  linux-image-4.15.0-45-generic linux-image-4.15.0-46-generic
  linux-image-4.15.0-47-generic linux-image-4.15.0-48-generic
  linux-image-4.15.0-50-generic linux-modules-4.15.0-23-generic
  linux-modules-4.15.0-29-generic linux-modules-4.15.0-32-generic
  linux-modules-4.15.0-33-generic linux-modules-4.15.0-34-generic
  linux-modules-4.15.0-36-generic linux-modules-4.15.0-38-generic
  linux-modules-4.15.0-39-generic linux-modules-4.15.0-42-generic
  linux-modules-4.15.0-43-generic linux-modules-4.15.0-44-generic
  linux-modules-4.15.0-45-generic linux-modules-4.15.0-46-generic
  linux-modules-4.15.0-47-generic linux-modules-4.15.0-48-generic
  linux-modules-4.15.0-50-generic linux-modules-extra-4.15.0-23-generic
  linux-modules-extra-4.15.0-29-generic linux-modules-extra-4.15.0-32-generic
  linux-modules-extra-4.15.0-33-generic linux-modules-extra-4.15.0-34-generic
  linux-modules-extra-4.15.0-36-generic linux-modules-extra-4.15.0-38-generic
  linux-modules-extra-4.15.0-39-generic linux-modules-extra-4.15.0-42-generic
  linux-modules-extra-4.15.0-43-generic linux-modules-extra-4.15.0-44-generic
  linux-modules-extra-4.15.0-45-generic linux-modules-extra-4.15.0-46-generic
  linux-modules-extra-4.15.0-47-generic linux-modules-extra-4.15.0-48-generic
  linux-modules-extra-4.15.0-50-generic seahorse-daemon
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  polo-donation-plugins
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/170 kB of archives.
After this operation, 884 kB of additional disk space will be used.
Get:1 /home/bri/Documents/polo-donation-plugins-v18.8/polo-donation-plugins-v18.8-amd64.deb polo-donation-plugins amd64 18.8 [170 kB]
Selecting previously unselected package polo-donation-plugins.
(Reading database ... 964203 files and directories currently installed.)
Preparing to unpack .../polo-donation-plugins-v18.8-amd64.deb ...
Unpacking polo-donation-plugins (18.8) ...
Setting up polo-donation-plugins (18.8) ...

**Comment by bdkdavid** [comment]
Ran the above a few times

![Screenshot from 2019-07-21 23-25-52](https://user-images.githubusercontent.com/52471052/61610851-21056780-ac0f-11e9-8459-2b78910aa826.png)

**Comment by bdkdavid** [comment]
Yes, thank You! The help was very good!
