### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by als-creator** [teejee2008/polo#282]
I installed it via run, how can I remove it from the system now? my package manager doesn't find it in the installed ones, I don't want to search all its folders

**Comment by als-creator** [comment]
https://github.com/teejee2008/polo/blob/master/src/polo-uninstall

**Comment by Celestial-Vixen** [comment]
Adding this to the install page would be useful. Having the uninstall-script remove the shortcut created in /usr/share/applications would also be helpful.
