### ISSUE TITLE
key bindings: backspace, mouse back/fwd (suggestion)

### ISSUE THREAD

**Issue by Lupul** [teejee2008/polo#34]
Hello Tony, 
It would be nice to navigate using mouse buttons (back/fwd) and the backspace key.

**Comment by teejee2008** [comment]
18.6 will have support for navigating to previous folder with backspace key. 
I don't have a mouse with back/fwd buttons so I won't be able to add support for it.

**Comment by ivanmlerner** [comment]
Hey, there are three issues like this one, so I'll just comment on all. 
Implementing this should be as easy as using a key bind that listens to the XF86Back and XF86Forward buttons, should work for most kayboards. It could also be useful to set key binds for XF86HomePage and XF86Favorites for home folder and bookmarks respectively. I'd do it myself, but I lack the programming knowledge.

**Comment by teejee2008** [comment]
Backspace key navigation was added in v18.6
