### ISSUE TITLE
Incorrect filesystem mountpoint detection

### ISSUE THREAD

**Issue by Lupul** [teejee2008/polo#49]
When a partition has multiple bind mounts then Polo will not point to the correct partition mountpoint path but to the last entry from /etc/mtab.

fstab:
`/dev/disk/by-uuid/$UUID /mnt/$UUID auto nosuid,nodev,nofail,x-gvfs-show 0 0`
`/mnt/$UUID/Apps                 /home/user/Apps        none    bind`
`/mnt/$UUID/Docs              /home/user/Docs     none    bind`

mtab: 
`/dev/sda3 /mnt/$UUID ext4 rw,nosuid,nodev,relatime,data=ordered 0 0`
`/dev/sda3 /home/user/Docs ext4 rw,nosuid,nodev,relatime,data=ordered 0 0`
`/dev/sda3 /home/user/Apps ext4 rw,nosuid,nodev,relatime,data=ordered 0 0`

expected result: Clicking on 'sda3' should open '/mnt/$UUID' instead it opens '/home/user/Apps'

**Comment by teejee2008** [comment]
Fixed in Beta 5
