### ISSUE TITLE
Add option for single-instance mode

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/polo#54]
Unknown 15 April 2017 at 13:33
Will Polo be able to run in a "single instance mode"? For example Polo is running and I open a directory from a web browser (or any other program), instead of opening a new instance of Polo it will open a tab in the running instance.

**Comment by teejee2008** [comment]
Add an option in settings for single instance mode. Make this option default?

**Comment by fbg13** [comment]
One more thing. If opening a directory that is already open, don't open another tab, just focus the opened one.
