### ISSUE TITLE
Add an option in View menu to calculate folder sizes

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/polo#58]

**Comment by Lupul** [comment]
Very good idea with this feature, was addicted to it when I was using "DirectoryOpus" on Windows.
My suggestion is to have a keyboard shortcut that fires one time the "calculate folder size" event for the current folder.

**Comment by teejee2008** [comment]
Added in Beta 5. Use CTRL+E or option in Menubar -> Tools
