### ISSUE TITLE
Hide close button for tabs

### ISSUE THREAD

**Issue by fbg13** [teejee2008/polo#64]
![6892e6ea7719447b964aa6ec7d4bded1-0](https://cloud.githubusercontent.com/assets/6839895/25071766/4fbd3e40-22c8-11e7-8aa3-0340e2340b60.jpg)

**Comment by drohm** [comment]
I'd say make it an option in Settings?  If you do plan to hide the 'X' button for tabs, maybe add the ability to double-click the tab to close it?

**Comment by fbg13** [comment]
Of course it should be optional and with a way to close them, i suggest middle click just like a browser tab.

**Comment by teejee2008** [comment]
Added setting to hide close button. Tabs can now be closed with middle click and using right-click menu.
