### ISSUE TITLE
Address bar

### ISSUE THREAD

**Issue by fabioluciano** [teejee2008/polo#65]
Hi Tony!

Congratulations on this amazing package!

I dont know if the xfce(gtk2) are in your radar now, but the app looks ugly on then.

On Left pcmanfm, and on the right polo.

![1_003](https://cloud.githubusercontent.com/assets/499057/25075097/81c874b2-22e2-11e7-9d5c-9f600531f810.png)

**Comment by teejee2008** [comment]
Are you using Xubuntu 16.04 ? I'll fix this in the next beta.

**Comment by fabioluciano** [comment]
This happens in 16.04 and 17.04.

Em dom, 16 de abr de 2017 23:38, Tony George <notifications@github.com>
escreveu:

**Comment by teejee2008** [comment]
Fixed in Beta 5
