### ISSUE TITLE
Collapse Devices in Side Panel

### ISSUE THREAD

**Issue by drohm** [teejee2008/polo#67]
When clicking on the '-' icon for Devices, it doesn't collapse the view for it.  Basically nothing happens.

**Comment by drohm** [comment]
I just realized that I can't collapse any section (Places, Bookmarks, Devices) in the side panel, not just the Devices section.  Looks to be related.

**Comment by Lupul** [comment]
I can also confirm this with Polo.beta4 and it was working correctly in beta3

**Comment by teejee2008** [comment]
Fixed in Beta 5
