### ISSUE TITLE
Right-clicking 'X' on Tab Closes Tab

### ISSUE THREAD

**Issue by drohm** [teejee2008/polo#68]
I'm not sure if this is desired behavior, but I was expecting to see some sort of context dialog for possibly more options.  Instead, it closed the tab.

**Comment by drohm** [comment]
Hi @teejee2008, just curious, was this the desired behavior or did you add a context menu to the right-click?

**Comment by teejee2008** [comment]
Context menu is displayed only on right-clicking the tab name. The X is a button for closing the tab. Logically, the X button should respond only to left-click and should not display a context-menu, which is what I have done now.
