### ISSUE TITLE
Tab Name and 'X' Button Too Close

### ISSUE THREAD

**Issue by drohm** [teejee2008/polo#69]
![tab-close-button-too-close](https://cloud.githubusercontent.com/assets/184959/25080680/e11d6cb6-2313-11e7-9524-d4d9dc156db5.png)

It's very easy to accidentally hit the 'X' button and close a tab when switching between multiple tabs.  Maybe you could add a set amount of space between the tab name and the 'X' button?

**Comment by teejee2008** [comment]
Added a spacing of 10px
