### ISSUE TITLE
Option to Hide Unmount Buttons for Devices

### ISSUE THREAD

**Issue by drohm** [teejee2008/polo#70]
![devices-umount-button](https://cloud.githubusercontent.com/assets/184959/25080747/46d3e058-2314-11e7-8c7e-646d20e5eebc.png)

I'd like the option to hide the 'Unmount' button listed next to each device.  I can see accidentally unmounting an important drive/partition.  It's easily recoverable, but if you did unmount a drive it would be a major pain.  Hiding would be nice here.  Maybe have the unmount option if you right-click the drive/partition?

I can see having it shown for USB or external drives, but I don't want to have it displayed for my internal drives.

**Comment by teejee2008** [comment]
Added a setting to hide unmount and lock buttons in sidebar
