### ISSUE TITLE
NTFS Partitions show Null

### ISSUE THREAD

**Issue by drohm** [teejee2008/polo#71]
![drive-type-null](https://cloud.githubusercontent.com/assets/184959/25094236/2c664198-2364-11e7-82de-1cfdfa5c8752.png)

This particular drive has one partition and it's NTFS, but shows null for the type.  I have a couple other NTFS partitions and they all show null for their type.  My ext4 partitions show as ext3/4

**Comment by teejee2008** [comment]
Fixed in Beta 5
