### ISSUE TITLE
Sidebar: dark theme setting doesn't get saved

### ISSUE THREAD

**Issue by Vistaus** [teejee2008/polo#77]
So I've successfully installed beta 4 on Solus (Linux) and it works terrific so far, thanks! The only issue I have is that the sidebar dark theme setting doesn't get saved (it's light and unchecked again after re-opening Polo). All other settings do get saved. How to fix this?

**Comment by teejee2008** [comment]
Fixed in Beta 5

**Comment by Vistaus** [comment]
Looking forward to beta 5 then. Thanks for fixing it so quickly! :smile:
