### ISSUE TITLE
[Archlinux] [Beta-4] Install ok but very laggy and left panel doesn't work

### ISSUE THREAD

**Issue by Aerya** [teejee2008/polo#83]
Hello,

It's runs on Archlinux (GTK) but it's really slow at browsing folders, especially /mnt dealing with local NFS shares and remote rClone Amazon shares while there's no lag using Thunar.

The main problem is the left panel doesn't work well:
 - Can't -/+ groups,
 - Can't add bookmarks,
 - Can't remove/add/modify places,
 - Activating the dark theme will - all the groups (and can't expand them).

![snapshot-2017-04-16-17-08-23-2017-04-28-10-17-58](https://cloud.githubusercontent.com/assets/26864765/25520477/5791ef48-2bfc-11e7-86f0-945271e9b4a3.png)

Is there a way to output the debug logs for a Polo session?

**Comment by teejee2008** [comment]
This was fixed in last beta
