### ISSUE TITLE
Smart extract for archives

### ISSUE THREAD

**Issue by fbg13** [teejee2008/polo#84]
> When you choose an archive file and click the right mouse button, there is the 'Extract Here (Smart)' menu.
It will function like below.

> If there is only one file/folder in an archive, it will extract to the 'Current Folder'.
In other cases, it will create a new folder and extract files to the 'Created Folder'.

https://www.bandisoft.com/bandizip/help/auto_dest/

**Comment by teejee2008** [comment]
The "Extract Here" option works like this - For an archive name **abc.zip**, Polo will extract it a folder named **abc** in the same location. If directory **abc** exists then archive is extracted to **abc (1)** and so on..

If there is a single item in archive then extracting to current folder is not a good idea as the user may not know the name of the file inside the archive, and will have to search the current folder to see what was extracted.

You can select "Extract To.." and click "OK" to extract to the same location without creating folders.

**Comment by fbg13** [comment]
> If there is a single item in archive then extracting to current folder is not a good idea as the user may not know the name of the file inside the archive

This should be an option, not the default, should have mentioned that.
But if the extraction currently available in polo differs only for single file archives then there's no need to add an option just for that.

I prefer to extract the archive without opening it and don't want to end up with tons of files and folders mixed with the files and folders already present, or if there's only one folder in the archive I don't want to go through one extra folder. I'm fine with extracting a single file in a new folder.
