### ISSUE TITLE
Fix UI issues with Greybird theme on Xubuntu

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/polo#86]
* Pathbar padding is incorrect
* Symbolic icons in toolbar look washed-out. Use non-symbolic icons for grey-bird theme?
* Sidebar dark theme makes items unreadable

**Comment by Vistaus** [comment]
Same with other GTK themes. It would be nice if Polo respected the system theme (like other file managers do) :)

**Comment by teejee2008** [comment]
Polo Beta 10 will not use the system GTK theme by default. A copy of Arc GTK theme is included with Beta 10 and will be used by default for the UI.

An option is added to Settings to change the Gtk theme used for the UI. Any installed theme can be selected.
