### ISSUE TITLE
Add support for XDG user directories - non-default configured variables

### ISSUE THREAD

**Issue by gpchelkin** [teejee2008/polo#88]
Make directory links in **Places** follow the **XDG user directories** set by user and not default (e.g. I use `~/.config/user-dirs.dirs` file to set my dirs). You could query configured directories with `xdg-user-dir`:
```
~ > xdg-user-dir MUSIC
/home/gpchelkin/Yandex.Disk.George/Music
```
More information:
- https://wiki.archlinux.org/index.php/XDG_user_directories
- https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by teejee2008** [comment]
Fixed in Beta 6
