### ISSUE TITLE
Device of same type mixes partitions

### ISSUE THREAD

**Issue by drohm** [teejee2008/polo#89]
I have two Samsung 950 Pro 512GB drives.  The side bar lists both devices, but when I expand one, it always shows the partitions underneath the last 950 Pro in the list.  Also, when I expand both devices, all partitions (for both drives) are listed underneath the last 950 Pro in the list.

All devices, none expanded:
![polo-devices-same-drive](https://cloud.githubusercontent.com/assets/184959/25792628/ae72c80a-3395-11e7-9286-bb31a6d1532a.png)

Now when I expand the first 950 Pro, it lists the partitions under the wrong 950 Pro, that I haven't expanded:
![polo-devices-partitions-wrong-drive](https://cloud.githubusercontent.com/assets/184959/25792639/c4171a8a-3395-11e7-97a7-0fff6ab9e3a9.png)

When I expand both 950 Pro's, it lists all partitions for both 950's under the last one:
![polo-devices-all-partitions-wrong-drive](https://cloud.githubusercontent.com/assets/184959/25792656/d4685f52-3395-11e7-9300-2f7d2aa16957.png)

**Comment by drohm** [comment]
I should also mention, some of the partitions are missing:

For the first 950 Pro, there should be:
* nvme0n1p1 (swap)
* nvme0n1p2 (ext4)
* nvme0n1p3 (ext4)

and for the second 950 Pro, there should be:
* nvme1n1p1 (ntfs)
* nvme1n1p2 (fat32)
* nvme1n1p3 (recovery)
* nvme1n1p4 (ntfs)

The first 950 Pro (3 partitions) is my linux drive while the second 950 Pro (4 partitions) is my Windows drive.

**Comment by teejee2008** [comment]
It looks like the parent-child relationship between partitions and disk is not detected correctly by lsblk.
Please provide the output of following command:
`lsblk --pairs --output NAME,KNAME,PKNAME,TYPE`

**Comment by drohm** [comment]
Looks fine to me.  The two 950 Pro's come through as `nvme1n1` and `nvme0n1`:
```
lsblk --pairs --output NAME,KNAME,PKNAME,TYPE
NAME="sda" KNAME="sda" PKNAME="" TYPE="disk"
NAME="sda1" KNAME="sda1" PKNAME="sda" TYPE="part"
NAME="sdb" KNAME="sdb" PKNAME="" TYPE="disk"
NAME="sdb1" KNAME="sdb1" PKNAME="sdb" TYPE="part"
NAME="sdc" KNAME="sdc" PKNAME="" TYPE="disk"
NAME="sdc1" KNAME="sdc1" PKNAME="sdc" TYPE="part"
NAME="sdc2" KNAME="sdc2" PKNAME="sdc" TYPE="part"
NAME="nvme1n1" KNAME="nvme1n1" PKNAME="" TYPE="disk"
NAME="nvme0n1" KNAME="nvme0n1" PKNAME="" TYPE="disk"
NAME="nvme1n1p1" KNAME="nvme1n1p1" PKNAME="nvme1n1" TYPE="part"
NAME="nvme1n1p2" KNAME="nvme1n1p2" PKNAME="nvme1n1" TYPE="part"
NAME="nvme1n1p3" KNAME="nvme1n1p3" PKNAME="nvme1n1" TYPE="part"
NAME="nvme1n1p4" KNAME="nvme1n1p4" PKNAME="nvme1n1" TYPE="part"
NAME="nvme0n1p1" KNAME="nvme0n1p1" PKNAME="nvme0n1" TYPE="part"
NAME="nvme0n1p2" KNAME="nvme0n1p2" PKNAME="nvme0n1" TYPE="part"
NAME="nvme0n1p3" KNAME="nvme0n1p3" PKNAME="nvme0n1" TYPE="part"
```

**Comment by teejee2008** [comment]
Looks like something's wrong in my code. I'll fix this in the next beta.

**Comment by teejee2008** [comment]
Fixed in Beta 6

**Comment by Lupul** [comment]
@drohm partitions without filesystems(like swap and extended part) are not expected to show up, related issue : #44

**Comment by drohm** [comment]
@Lupul I agree, it's just that the partitions that were being displayed were shown under the wrong device.

**Comment by Lupul** [comment]
I was addressing your second post/comment.

**Comment by teejee2008** [comment]
@drohm Could you confirm if partitions are listed under the correct disk with b6? 

Fixing this issue caused #44.

**Comment by drohm** [comment]
It's fixed, looks great.
