### ISSUE TITLE
Localized folder names: path not found

### ISSUE THREAD

**Issue by Vistaus** [teejee2008/polo#93]
I'm using English (US) as my system language normally, but I did notice that Polo doesn't like localized folder names on systems using some other language than English. It returns "path not found". To be clear: I'm talking about the default folders in the sidebar.

I think that needs to be fixed 😉

**Comment by teejee2008** [comment]
Fixed in Beta 6

**Comment by Vistaus** [comment]
Thanks for the quick fix! :)
