### ISSUE TITLE
Headerbar: titlebar buttons on wrong side

### ISSUE THREAD

**Issue by Vistaus** [teejee2008/polo#98]
I love the new Headerbar! But the titlebar buttons are on the right side. I have them set system-wide on the left side. It would be great if Polo would respect that setting :)

**Comment by teejee2008** [comment]
I'll add an option in Settings window

**Comment by Vistaus** [comment]
Thanks for the quick response and for adding it in the settings windows soon :)

**Comment by teejee2008** [comment]
Added in Beta 7
